language: java

env:
  - NODE_VERSION="12.13.1"
  
services:
  - docker

addons:
  sonarcloud:
    organization: "rolandogdp" # the key of the org you chose at step #3
    token:
    secure: "sGbeW42Rm9WB8sLbsCvNJkhad0enYmBpX7un+1U5npu3WmaipF4xntMMp0OluOBKPaaZSWYtXt3+QqdbLjFEprxRorXRBXFB4pSNfRN5uoooFb2Ggbd2vYkVTvBfayyzVNBaQbd4VTffwfFEMWvrUlGolHHfwV4z/lxBENr0fLKxGORKA3cM7Bzi2U1I8LMGelv0Vk4L6jgDKxPKw1jYTvtz/rOmws9UQqhkuZ1X46MDplIYXlkJh6w+j2H7DSv+Dq7WGb16QnWwAhKVLpwEk+pjAz+7oD6y5irYT3IWvyoSo0aMJoB8arRTLZPl80seXWVcfLdSs0LM63EgSl67KjMZ6wRk3ep5VpBOiOkXrhvxTpFDIJhTXX5kzb4gXWXSktRzmWJEFWu3QIvYwcDq24apRsbTYnPA+ysqMjR5C7jHhSiRTY/M4NE1VoDHy8+1mdOpA7S2/oojKm25wUVMAuZ6F6vVf45ENKVyiFlcqSUn7cIo32PMBcpHIOw+NCfnGFDDp974j04VqXG870TBpb5UZJg+id9BNicUfhAkn1RNJuMelSJuTbAnZL/DXJ1VSxzl5y2VQNPvHtl6sIEnarTSEn2+RiLBlPO5bQu6TKWY96VtyQQvIZHEnOpYfIYpQFoIcrYQg+MGPl5Ow9Ub0PjGGwLGiVbL/pa5Mm1z8Fk="
cache:
    directories:
      - .autoconf
      - $HOME/.m2
      - node_modules

jobs:
  include:
    - stage: Prepare
      script:
      - nvm install $NODE_VERSION
      - mvn install -N -DskipTests=true -Dmaven.javadoc.skip=true -B -V
    - stage : Build
      script:
      - mvn install -Ppackage-docker-image  
      - echo "$DOCKER_USERNAME"
      - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin
      - docker tag unige/api-gateway stevehostettler/api-gateway:latest
      - docker tag unige/regulatory-service stevehostettler/regulatory-service:latest
      - docker tag unige/valuation-service stevehostettler/valuation-service:latest
      - docker tag unige/instrument-service stevehostettler/instrument-service:latest
      - docker tag unige/counterparty-service stevehostettler/counterparty-service:latest     
      - docker push stevehostettler/api-gateway:latest
      - docker push stevehostettler/regulatory-service:latest
      - docker push stevehostettler/valuation-service:latest
      - docker push stevehostettler/instrument-service:latest
      - docker push stevehostettler/counterparty-service:latest
      - mvn sonar:sonar -Dsonar.projectKey=hostettler_microservices -Dsonar.organization=hostettler-github -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=10de2947edc0e089a82360cb2d1aa97482fafc28     
    - stage : Build
      script:
      - cd web-ui
      - pwd
      - npm -v
      - npm install
      - npm update
      - npm run-script build --prod
      - docker build -t unige/web-ui .
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin      
      - docker tag unige/web-ui stevehostettler/web-ui:latest      
      - docker push stevehostettler/web-ui:latest
