language: java

env:
  - NODE_VERSION="12.13.1"
  
services:
  - docker

addons:
  sonarcloud:
    organization: "rolandogdp" # the key of the org you chose at step #3
    
cache:
    directories:
      - .autoconf
      - $HOME/.m2
      - node_modules

jobs:
  include:
    - stage: Prepare
      script:
      - nvm install $NODE_VERSION
      - mvn install -N -DskipTests=true -Dmaven.javadoc.skip=true -B -V
    - stage : Build
      script:
      - mvn install -Ppackage-docker-image  
      - echo "$DOCKER_USERNAME"
      - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin
      - docker tag unige/api-gateway rolandock/api-gateway:latest
      - docker tag unige/regulatory-service rolandock/regulatory-service:latest
      - docker tag unige/valuation-service rolandock/valuation-service:latest
      - docker tag unige/instrument-service rolandock/instrument-service:latest
      - docker tag unige/counterparty-service rolandock/counterparty-service:latest     
      - docker push rolandock/api-gateway:latest
      - docker push rolandock/regulatory-service:latest
      - docker push rolandock/valuation-service:latest
      - docker push rolandock/instrument-service:latest
      - docker push rolandock/counterparty-service:latest
      - mvn sonar:sonar -Dsonar.projectKey=rolandogdp_microservices -Dsonar.organization=rolandogdp -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=     
    - stage : Build
      script:
      - cd web-ui
      - pwd
      - npm -v
      - npm install
      - npm update
      - npm run-script build --prod
      - docker build -t unige/web-ui .
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin      
      - docker tag unige/web-ui rolandock/web-ui:latest      
      - docker push rolandock/web-ui:latest
